# Generated by Django 6.0.5 on 2026-08-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='created_by_email',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
